spring.application.name=drone-project-manager

# Multitenancy
spring.jpa.properties.hibernate.multiTenancy=SCHEMA

# Active Spring Profile
spring.profiles.active=local
#spring.profiles.active=prod

# JPA (Hibernate) Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

# Spring image upload configuration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=1000MB
spring.servlet.multipart.max-request-size=1000MB