# Datasource config
spring.datasource.url=jdbc:postgresql://localhost:5432/drone_project_manager
spring.datasource.username=CHANGE_ME
spring.datasource.password=CHANGE_ME
spring.datasource.driver-class-name=org.postgresql.Driver

logging.level.root=INFO