spring.application.name=drone-project-manager

# Active Spring Profile
spring.profiles.active=local
#spring.profiles.active=prod

# JPA (Hibernate) Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false